/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "65ed616c6e8ee3fe0ad64fe83796c020644d42af"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
